language: java
jdk: oraclejdk8
script:
- cd unleash-server && npm install && npm test-travis
- cd .. && cd unleash-client-java && mvn test
notifications:
  hipchat:
    rooms:
      secure: GiIDk52xccnUKnevjLE+w6eUXg0jfV7oOmagw5VnOV5jXGUxdzMk/Q9um+oSClEPE51IvF76zoFEKPIX/CNdjgalEr+CZADy1gene/YRGrNgrXmYYmiU1/dNzelpla1WpKPrY2pkbOgKxrCR9ScID+pMs6vzvJnPwK9vu66W61U=
