on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [8,11]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.version }}
      - name: Build, test, coverage
        run: ./mvnw clean test jacoco:report coveralls:report
  java17:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build, test, coverage
        run: ./mvnw clean test jacoco:report coveralls:report
        env:
          MAVEN_OPTS: "--add-opens java.base/java.net=ALL-UNNAMED"

